### ISSUE TITLE
[FEATURE] Upload the finished builded Jarfiles for Ported Wildlife Gender Mod pls 

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [celestialfault/bridge-server#3]
I Know this is not the right place for creating a issue but since its a direct port only Pull Requests are Possible so I wanted to ask here if it would be possible for you to do that :>

**Comment by celestialfault** [comment]
.. You could've also just [commented this on the PR in question](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/pull/191).

(and, for the record, you could've *also* downloaded it from my repo's [github actions](https://github.com/celestialfault/WildfireFemaleGenderMod/actions).)
